# Set theme
remote_theme: daviddarnes/alembic@main
theme: alembic-jekyll-theme

# File excludes
exclude:
#- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Nic Blog" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/NicLogo.jpg" # Site logo, also used in jekyll-seo-tag
description: "Welcom to Nic's Blog" # Site description and default description, also used in jekyll-seo-tag
url: "https://nicheblog.github.io/blog/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/nicheblog"
email: "heningchine@outlook.com"

permalink: pretty

# Pagination
paginate: 8
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Category
  url: /categories/
- title: Search
  url: /search/
# - title: Elements
#   url: /elements/
# - title: Fork Alembic
#  url: https://github.com/daviddarnes/alembic

# Footer nav
navigation_footer:
- title: Created by @NicHe
  url: https://nicheblog.github.io

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to Nic's Blog
    feature_image: "https://picsum.photos/id/510/1300/400/"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
